/** Generated by tools/build-bsb-assets.py — do not hand-edit. */
export interface BookEntry {
  osis: string;
  bsb: string;
  name: string;
  chapters: number;
  testament: 'OT' | 'NT';
}

export const BOOKS: BookEntry[] = [
  { osis: 'Gen', bsb: 'GEN', name: 'Genesis', chapters: 50, testament: 'OT' },
  { osis: 'Exod', bsb: 'EXO', name: 'Exodus', chapters: 40, testament: 'OT' },
  { osis: 'Lev', bsb: 'LEV', name: 'Leviticus', chapters: 27, testament: 'OT' },
  { osis: 'Num', bsb: 'NUM', name: 'Numbers', chapters: 36, testament: 'OT' },
  { osis: 'Deut', bsb: 'DEU', name: 'Deuteronomy', chapters: 34, testament: 'OT' },
  { osis: 'Josh', bsb: 'JOS', name: 'Joshua', chapters: 24, testament: 'OT' },
  { osis: 'Judg', bsb: 'JDG', name: 'Judges', chapters: 21, testament: 'OT' },
  { osis: 'Ruth', bsb: 'RUT', name: 'Ruth', chapters: 4, testament: 'OT' },
  { osis: '1Sam', bsb: '1SA', name: '1 Samuel', chapters: 31, testament: 'OT' },
  { osis: '2Sam', bsb: '2SA', name: '2 Samuel', chapters: 24, testament: 'OT' },
  { osis: '1Kgs', bsb: '1KI', name: '1 Kings', chapters: 22, testament: 'OT' },
  { osis: '2Kgs', bsb: '2KI', name: '2 Kings', chapters: 25, testament: 'OT' },
  { osis: '1Chr', bsb: '1CH', name: '1 Chronicles', chapters: 29, testament: 'OT' },
  { osis: '2Chr', bsb: '2CH', name: '2 Chronicles', chapters: 36, testament: 'OT' },
  { osis: 'Ezra', bsb: 'EZR', name: 'Ezra', chapters: 10, testament: 'OT' },
  { osis: 'Neh', bsb: 'NEH', name: 'Nehemiah', chapters: 13, testament: 'OT' },
  { osis: 'Esth', bsb: 'EST', name: 'Esther', chapters: 10, testament: 'OT' },
  { osis: 'Job', bsb: 'JOB', name: 'Job', chapters: 42, testament: 'OT' },
  { osis: 'Ps', bsb: 'PSA', name: 'Psalms', chapters: 150, testament: 'OT' },
  { osis: 'Prov', bsb: 'PRO', name: 'Proverbs', chapters: 31, testament: 'OT' },
  { osis: 'Eccl', bsb: 'ECC', name: 'Ecclesiastes', chapters: 12, testament: 'OT' },
  { osis: 'Song', bsb: 'SNG', name: 'Song of Songs', chapters: 8, testament: 'OT' },
  { osis: 'Isa', bsb: 'ISA', name: 'Isaiah', chapters: 66, testament: 'OT' },
  { osis: 'Jer', bsb: 'JER', name: 'Jeremiah', chapters: 52, testament: 'OT' },
  { osis: 'Lam', bsb: 'LAM', name: 'Lamentations', chapters: 5, testament: 'OT' },
  { osis: 'Ezek', bsb: 'EZK', name: 'Ezekiel', chapters: 48, testament: 'OT' },
  { osis: 'Dan', bsb: 'DAN', name: 'Daniel', chapters: 12, testament: 'OT' },
  { osis: 'Hos', bsb: 'HOS', name: 'Hosea', chapters: 14, testament: 'OT' },
  { osis: 'Joel', bsb: 'JOL', name: 'Joel', chapters: 3, testament: 'OT' },
  { osis: 'Amos', bsb: 'AMO', name: 'Amos', chapters: 9, testament: 'OT' },
  { osis: 'Obad', bsb: 'OBA', name: 'Obadiah', chapters: 1, testament: 'OT' },
  { osis: 'Jon', bsb: 'JON', name: 'Jonah', chapters: 4, testament: 'OT' },
  { osis: 'Mic', bsb: 'MIC', name: 'Micah', chapters: 7, testament: 'OT' },
  { osis: 'Nah', bsb: 'NAM', name: 'Nahum', chapters: 3, testament: 'OT' },
  { osis: 'Hab', bsb: 'HAB', name: 'Habakkuk', chapters: 3, testament: 'OT' },
  { osis: 'Zeph', bsb: 'ZEP', name: 'Zephaniah', chapters: 3, testament: 'OT' },
  { osis: 'Hag', bsb: 'HAG', name: 'Haggai', chapters: 2, testament: 'OT' },
  { osis: 'Zech', bsb: 'ZEC', name: 'Zechariah', chapters: 14, testament: 'OT' },
  { osis: 'Mal', bsb: 'MAL', name: 'Malachi', chapters: 4, testament: 'OT' },
  { osis: 'Matt', bsb: 'MAT', name: 'Matthew', chapters: 28, testament: 'NT' },
  { osis: 'Mark', bsb: 'MRK', name: 'Mark', chapters: 16, testament: 'NT' },
  { osis: 'Luke', bsb: 'LUK', name: 'Luke', chapters: 24, testament: 'NT' },
  { osis: 'John', bsb: 'JHN', name: 'John', chapters: 21, testament: 'NT' },
  { osis: 'Acts', bsb: 'ACT', name: 'Acts', chapters: 28, testament: 'NT' },
  { osis: 'Rom', bsb: 'ROM', name: 'Romans', chapters: 16, testament: 'NT' },
  { osis: '1Cor', bsb: '1CO', name: '1 Corinthians', chapters: 16, testament: 'NT' },
  { osis: '2Cor', bsb: '2CO', name: '2 Corinthians', chapters: 13, testament: 'NT' },
  { osis: 'Gal', bsb: 'GAL', name: 'Galatians', chapters: 6, testament: 'NT' },
  { osis: 'Eph', bsb: 'EPH', name: 'Ephesians', chapters: 6, testament: 'NT' },
  { osis: 'Phil', bsb: 'PHP', name: 'Philippians', chapters: 4, testament: 'NT' },
  { osis: 'Col', bsb: 'COL', name: 'Colossians', chapters: 4, testament: 'NT' },
  { osis: '1Thess', bsb: '1TH', name: '1 Thessalonians', chapters: 5, testament: 'NT' },
  { osis: '2Thess', bsb: '2TH', name: '2 Thessalonians', chapters: 3, testament: 'NT' },
  { osis: '1Tim', bsb: '1TI', name: '1 Timothy', chapters: 6, testament: 'NT' },
  { osis: '2Tim', bsb: '2TI', name: '2 Timothy', chapters: 4, testament: 'NT' },
  { osis: 'Titus', bsb: 'TIT', name: 'Titus', chapters: 3, testament: 'NT' },
  { osis: 'Phlm', bsb: 'PHM', name: 'Philemon', chapters: 1, testament: 'NT' },
  { osis: 'Heb', bsb: 'HEB', name: 'Hebrews', chapters: 13, testament: 'NT' },
  { osis: 'Jas', bsb: 'JAS', name: 'James', chapters: 5, testament: 'NT' },
  { osis: '1Pet', bsb: '1PE', name: '1 Peter', chapters: 5, testament: 'NT' },
  { osis: '2Pet', bsb: '2PE', name: '2 Peter', chapters: 3, testament: 'NT' },
  { osis: '1John', bsb: '1JN', name: '1 John', chapters: 5, testament: 'NT' },
  { osis: '2John', bsb: '2JN', name: '2 John', chapters: 1, testament: 'NT' },
  { osis: '3John', bsb: '3JN', name: '3 John', chapters: 1, testament: 'NT' },
  { osis: 'Jude', bsb: 'JUD', name: 'Jude', chapters: 1, testament: 'NT' },
  { osis: 'Rev', bsb: 'REV', name: 'Revelation', chapters: 22, testament: 'NT' },
];

const byOsis = new Map(BOOKS.map((book) => [book.osis, book]));

export function bookByOsis(osis: string): BookEntry | null {
  return byOsis.get(osis) ?? null;
}

export function booksByTestament(testament: 'OT' | 'NT'): BookEntry[] {
  return BOOKS.filter((book) => book.testament === testament);
}
