/**
 * Bundled BSB content access. Single-translation build (owner decision):
 * every surface reads version identity from `activeTranslation`, never from
 * hardcoded strings, so a future second translation only extends this file.
 *
 * Assets are generated by `tools/build-bsb-assets.py` from the local `bsb/`
 * dataset (never committed). Metro bundles the per-book files; they parse on
 * first chapter open — the SQLite content cache (Phase 8) replaces this.
 */

import { bookByOsis } from './books';

// Metro provides require() at runtime for bundled JSON assets.
declare const require: (path: string) => unknown;

export interface TranslationRecord {
  id: string;
  name: string;
  short: string;
  attribution: string;
  licenseUrl: string;
  rightsBasis: string;
}

export const activeTranslation: TranslationRecord = {
  id: 'BSB',
  name: 'Berean Standard Bible',
  short: 'BSB',
  attribution: 'Berean Standard Bible · BSB',
  licenseUrl: 'https://berean.bible/',
  rightsBasis: 'Owner-confirmed berean.bible distribution terms; formal sign-off pending (CONTENT_RIGHTS.md).',
};

export type ChapterBlock =
  | { kind: 'heading'; text: string }
  | { kind: 'verse'; number: number; text: string };

export interface ChapterContent {
  bookOsis: string;
  bookName: string;
  chapter: number;
  blocks: ChapterBlock[];
  verseCount: number;
}

interface BookAsset {
  osis: string;
  name: string;
  chapters: Array<{ n: number; blocks: Array<{ t: string; n?: number; text: string }> }>;
}

// Static map so Metro bundles each book file. Parsed on first chapter open.
const BOOK_ASSETS: Record<string, () => unknown> = {
  Gen: () => require('../../assets/scripture/bsb/Gen.json'),
  Exod: () => require('../../assets/scripture/bsb/Exod.json'),
  Lev: () => require('../../assets/scripture/bsb/Lev.json'),
  Num: () => require('../../assets/scripture/bsb/Num.json'),
  Deut: () => require('../../assets/scripture/bsb/Deut.json'),
  Josh: () => require('../../assets/scripture/bsb/Josh.json'),
  Judg: () => require('../../assets/scripture/bsb/Judg.json'),
  Ruth: () => require('../../assets/scripture/bsb/Ruth.json'),
  '1Sam': () => require('../../assets/scripture/bsb/1Sam.json'),
  '2Sam': () => require('../../assets/scripture/bsb/2Sam.json'),
  '1Kgs': () => require('../../assets/scripture/bsb/1Kgs.json'),
  '2Kgs': () => require('../../assets/scripture/bsb/2Kgs.json'),
  '1Chr': () => require('../../assets/scripture/bsb/1Chr.json'),
  '2Chr': () => require('../../assets/scripture/bsb/2Chr.json'),
  Ezra: () => require('../../assets/scripture/bsb/Ezra.json'),
  Neh: () => require('../../assets/scripture/bsb/Neh.json'),
  Esth: () => require('../../assets/scripture/bsb/Esth.json'),
  Job: () => require('../../assets/scripture/bsb/Job.json'),
  Ps: () => require('../../assets/scripture/bsb/Ps.json'),
  Prov: () => require('../../assets/scripture/bsb/Prov.json'),
  Eccl: () => require('../../assets/scripture/bsb/Eccl.json'),
  Song: () => require('../../assets/scripture/bsb/Song.json'),
  Isa: () => require('../../assets/scripture/bsb/Isa.json'),
  Jer: () => require('../../assets/scripture/bsb/Jer.json'),
  Lam: () => require('../../assets/scripture/bsb/Lam.json'),
  Ezek: () => require('../../assets/scripture/bsb/Ezek.json'),
  Dan: () => require('../../assets/scripture/bsb/Dan.json'),
  Hos: () => require('../../assets/scripture/bsb/Hos.json'),
  Joel: () => require('../../assets/scripture/bsb/Joel.json'),
  Amos: () => require('../../assets/scripture/bsb/Amos.json'),
  Obad: () => require('../../assets/scripture/bsb/Obad.json'),
  Jon: () => require('../../assets/scripture/bsb/Jon.json'),
  Mic: () => require('../../assets/scripture/bsb/Mic.json'),
  Nah: () => require('../../assets/scripture/bsb/Nah.json'),
  Hab: () => require('../../assets/scripture/bsb/Hab.json'),
  Zeph: () => require('../../assets/scripture/bsb/Zeph.json'),
  Hag: () => require('../../assets/scripture/bsb/Hag.json'),
  Zech: () => require('../../assets/scripture/bsb/Zech.json'),
  Mal: () => require('../../assets/scripture/bsb/Mal.json'),
  Matt: () => require('../../assets/scripture/bsb/Matt.json'),
  Mark: () => require('../../assets/scripture/bsb/Mark.json'),
  Luke: () => require('../../assets/scripture/bsb/Luke.json'),
  John: () => require('../../assets/scripture/bsb/John.json'),
  Acts: () => require('../../assets/scripture/bsb/Acts.json'),
  Rom: () => require('../../assets/scripture/bsb/Rom.json'),
  '1Cor': () => require('../../assets/scripture/bsb/1Cor.json'),
  '2Cor': () => require('../../assets/scripture/bsb/2Cor.json'),
  Gal: () => require('../../assets/scripture/bsb/Gal.json'),
  Eph: () => require('../../assets/scripture/bsb/Eph.json'),
  Phil: () => require('../../assets/scripture/bsb/Phil.json'),
  Col: () => require('../../assets/scripture/bsb/Col.json'),
  '1Thess': () => require('../../assets/scripture/bsb/1Thess.json'),
  '2Thess': () => require('../../assets/scripture/bsb/2Thess.json'),
  '1Tim': () => require('../../assets/scripture/bsb/1Tim.json'),
  '2Tim': () => require('../../assets/scripture/bsb/2Tim.json'),
  Titus: () => require('../../assets/scripture/bsb/Titus.json'),
  Phlm: () => require('../../assets/scripture/bsb/Phlm.json'),
  Heb: () => require('../../assets/scripture/bsb/Heb.json'),
  Jas: () => require('../../assets/scripture/bsb/Jas.json'),
  '1Pet': () => require('../../assets/scripture/bsb/1Pet.json'),
  '2Pet': () => require('../../assets/scripture/bsb/2Pet.json'),
  '1John': () => require('../../assets/scripture/bsb/1John.json'),
  '2John': () => require('../../assets/scripture/bsb/2John.json'),
  '3John': () => require('../../assets/scripture/bsb/3John.json'),
  Jude: () => require('../../assets/scripture/bsb/Jude.json'),
  Rev: () => require('../../assets/scripture/bsb/Rev.json'),
};

/** Whole-chapter content. Returns null for unknown books or chapters. */
export function getChapter(bookOsis: string, chapter: number): ChapterContent | null {
  const entry = bookByOsis(bookOsis);
  const load = BOOK_ASSETS[bookOsis];
  if (!entry || !load || chapter < 1 || chapter > entry.chapters) return null;
  const asset = load() as BookAsset;
  const found = asset.chapters.find((item) => item.n === chapter);
  if (!found) return null;
  const blocks: ChapterBlock[] = found.blocks.map((block) =>
    block.t === 'h'
      ? { kind: 'heading', text: block.text }
      : { kind: 'verse', number: block.n ?? 0, text: block.text },
  );
  return {
    bookOsis,
    bookName: entry.name,
    chapter,
    blocks,
    verseCount: blocks.filter((block) => block.kind === 'verse').length,
  };
}

/** Plain verse text, e.g. the daily verse. Null when absent. */
export function getVerseText(bookOsis: string, chapter: number, verse: number): string | null {
  const content = getChapter(bookOsis, chapter);
  if (!content) return null;
  const block = content.blocks.find(
    (item): item is { kind: 'verse'; number: number; text: string } =>
      item.kind === 'verse' && item.number === verse,
  );
  return block ? block.text : null;
}
