/**
 * Bundled Scripture content access. Every surface reads version identity
 * from `getActiveTranslation()`, never from hardcoded strings, and chapter
 * text through `getChapter`/`getVerseText`, which default to the selected
 * translation. Assets are generated by `tools/build-bsb-assets.py` from the
 * local `bsb/` dataset (never committed). Metro bundles the per-book files;
 * they parse on first chapter open — the SQLite content cache (Phase 8)
 * replaces this.
 *
 * Anchors stay translation-specific: only BSB has validated anchors, so
 * other translations render Scripture without the context layer until
 * per-translation anchors are reviewed.
 */

import { BOOKS, bookByOsis, type BookEntry } from './books';
import { BOOKS_TA } from './books_ta';
import { BOOKS_TE } from './books_te';

// Metro provides require() at runtime for bundled JSON assets.
declare const require: (path: string) => unknown;

export type ScriptureLanguage = 'en' | 'ta' | 'te';

export interface TranslationRecord {
  id: string;
  language: ScriptureLanguage;
  name: string;
  short: string;
  attribution: string;
  licenseUrl: string;
  rightsBasis: string;
  /** Testament labels in the translation language: [old, new]. */
  testaments: [string, string];
}

const TRANSLATIONS: Record<string, TranslationRecord> = {
  BSB: {
    id: 'BSB',
    language: 'en',
    name: 'Berean Standard Bible',
    short: 'BSB',
    attribution: 'Berean Standard Bible · BSB',
    licenseUrl: 'https://berean.bible/',
    rightsBasis:
      'Owner-confirmed berean.bible distribution terms; formal sign-off pending (CONTENT_RIGHTS.md).',
    testaments: ['Old Testament', 'New Testament'],
  },
  tam_irv: {
    id: 'tam_irv',
    language: 'ta',
    name: 'Indian Revised Version (Tamil)',
    short: 'IRV-TA',
    attribution: 'Indian Revised Version (Tamil) · IRV-TA',
    licenseUrl: 'https://ebible.org/Scriptures/details.php?id=tam2017',
    rightsBasis: 'Owner-confirmed: same basis as BSB (CONTENT_RIGHTS.md).',
    testaments: ['பழைய ஏற்பாடு', 'புதிய ஏற்பாடு'],
  },
  tel_irv: {
    id: 'tel_irv',
    language: 'te',
    name: 'Indian Revised Version (Telugu)',
    short: 'IRV-TE',
    attribution: 'Indian Revised Version (Telugu) · IRV-TE',
    licenseUrl: 'https://ebible.org/Scriptures/details.php?id=tel2017',
    rightsBasis: 'Owner-confirmed: same basis as BSB (CONTENT_RIGHTS.md).',
    testaments: ['పాత నిబంధన', 'క్రొత్త నిబంధన'],
  },
};

/** Translation ids in display order: English, Tamil, Telugu. */
export const TRANSLATION_ORDER = ['BSB', 'tam_irv', 'tel_irv'] as const;

let selectedId = 'BSB';

/** Active record; defaults to BSB until the user picks a translation. */
export function getActiveTranslation(): TranslationRecord {
  return TRANSLATIONS[selectedId] ?? TRANSLATIONS.BSB;
}

export function selectedTranslationId(): string {
  return selectedId;
}

export function translationById(id: string): TranslationRecord | null {
  return TRANSLATIONS[id] ?? null;
}

/** Select a bundled translation; unknown ids fail closed on BSB. */
export function selectTranslationId(id: string): boolean {
  if (!TRANSLATIONS[id]) return false;
  selectedId = id;
  return true;
}

/** Telugu and Tamil Scripture needs the Indic reading scale. */
export function isIndicTranslation(id: string): boolean {
  const record = TRANSLATIONS[id];
  return !!record && record.language !== 'en';
}

/** Localized book registry for a translation; unknown ids fail closed on English. */
export function booksFor(translationId: string): BookEntry[] {
  if (translationId === 'tam_irv') return BOOKS_TA;
  if (translationId === 'tel_irv') return BOOKS_TE;
  return BOOKS;
}

/** Book name in the translation language; falls back to the OSIS code. */
export function bookNameFor(osis: string, translationId: string): string {
  return booksFor(translationId).find((book) => book.osis === osis)?.name ?? osis;
}

/** "Nehemiah 2:4" in the translation language. */
export function verseLabel(
  bookOsis: string,
  chapter: number,
  verse: number,
  translationId: string,
): string {
  return `${bookNameFor(bookOsis, translationId)} ${chapter}:${verse}`;
}

/** "Nehemiah 2:1–8" in the translation language. */
export function rangeLabel(
  bookOsis: string,
  chapter: number,
  startVerse: number,
  endVerse: number,
  translationId: string,
): string {
  return `${bookNameFor(bookOsis, translationId)} ${chapter}:${startVerse}–${endVerse}`;
}

export type ChapterBlock =
  { kind: 'heading'; text: string } | { kind: 'verse'; number: number; text: string };

export interface ChapterContent {
  bookOsis: string;
  bookName: string;
  chapter: number;
  blocks: ChapterBlock[];
  verseCount: number;
}

interface BookAsset {
  osis: string;
  name: string;
  chapters: Array<{ n: number; blocks: Array<{ t: string; n?: number; text: string }> }>;
}

// Static maps so Metro bundles each book file. Parsed on first chapter open.
const BOOK_ASSETS: Record<string, Record<string, () => unknown>> = {
  BSB: {
    Gen: () => require('../../assets/scripture/bsb/Gen.json'),
    Exod: () => require('../../assets/scripture/bsb/Exod.json'),
    Lev: () => require('../../assets/scripture/bsb/Lev.json'),
    Num: () => require('../../assets/scripture/bsb/Num.json'),
    Deut: () => require('../../assets/scripture/bsb/Deut.json'),
    Josh: () => require('../../assets/scripture/bsb/Josh.json'),
    Judg: () => require('../../assets/scripture/bsb/Judg.json'),
    Ruth: () => require('../../assets/scripture/bsb/Ruth.json'),
    '1Sam': () => require('../../assets/scripture/bsb/1Sam.json'),
    '2Sam': () => require('../../assets/scripture/bsb/2Sam.json'),
    '1Kgs': () => require('../../assets/scripture/bsb/1Kgs.json'),
    '2Kgs': () => require('../../assets/scripture/bsb/2Kgs.json'),
    '1Chr': () => require('../../assets/scripture/bsb/1Chr.json'),
    '2Chr': () => require('../../assets/scripture/bsb/2Chr.json'),
    Ezra: () => require('../../assets/scripture/bsb/Ezra.json'),
    Neh: () => require('../../assets/scripture/bsb/Neh.json'),
    Esth: () => require('../../assets/scripture/bsb/Esth.json'),
    Job: () => require('../../assets/scripture/bsb/Job.json'),
    Ps: () => require('../../assets/scripture/bsb/Ps.json'),
    Prov: () => require('../../assets/scripture/bsb/Prov.json'),
    Eccl: () => require('../../assets/scripture/bsb/Eccl.json'),
    Song: () => require('../../assets/scripture/bsb/Song.json'),
    Isa: () => require('../../assets/scripture/bsb/Isa.json'),
    Jer: () => require('../../assets/scripture/bsb/Jer.json'),
    Lam: () => require('../../assets/scripture/bsb/Lam.json'),
    Ezek: () => require('../../assets/scripture/bsb/Ezek.json'),
    Dan: () => require('../../assets/scripture/bsb/Dan.json'),
    Hos: () => require('../../assets/scripture/bsb/Hos.json'),
    Joel: () => require('../../assets/scripture/bsb/Joel.json'),
    Amos: () => require('../../assets/scripture/bsb/Amos.json'),
    Obad: () => require('../../assets/scripture/bsb/Obad.json'),
    Jon: () => require('../../assets/scripture/bsb/Jon.json'),
    Mic: () => require('../../assets/scripture/bsb/Mic.json'),
    Nah: () => require('../../assets/scripture/bsb/Nah.json'),
    Hab: () => require('../../assets/scripture/bsb/Hab.json'),
    Zeph: () => require('../../assets/scripture/bsb/Zeph.json'),
    Hag: () => require('../../assets/scripture/bsb/Hag.json'),
    Zech: () => require('../../assets/scripture/bsb/Zech.json'),
    Mal: () => require('../../assets/scripture/bsb/Mal.json'),
    Matt: () => require('../../assets/scripture/bsb/Matt.json'),
    Mark: () => require('../../assets/scripture/bsb/Mark.json'),
    Luke: () => require('../../assets/scripture/bsb/Luke.json'),
    John: () => require('../../assets/scripture/bsb/John.json'),
    Acts: () => require('../../assets/scripture/bsb/Acts.json'),
    Rom: () => require('../../assets/scripture/bsb/Rom.json'),
    '1Cor': () => require('../../assets/scripture/bsb/1Cor.json'),
    '2Cor': () => require('../../assets/scripture/bsb/2Cor.json'),
    Gal: () => require('../../assets/scripture/bsb/Gal.json'),
    Eph: () => require('../../assets/scripture/bsb/Eph.json'),
    Phil: () => require('../../assets/scripture/bsb/Phil.json'),
    Col: () => require('../../assets/scripture/bsb/Col.json'),
    '1Thess': () => require('../../assets/scripture/bsb/1Thess.json'),
    '2Thess': () => require('../../assets/scripture/bsb/2Thess.json'),
    '1Tim': () => require('../../assets/scripture/bsb/1Tim.json'),
    '2Tim': () => require('../../assets/scripture/bsb/2Tim.json'),
    Titus: () => require('../../assets/scripture/bsb/Titus.json'),
    Phlm: () => require('../../assets/scripture/bsb/Phlm.json'),
    Heb: () => require('../../assets/scripture/bsb/Heb.json'),
    Jas: () => require('../../assets/scripture/bsb/Jas.json'),
    '1Pet': () => require('../../assets/scripture/bsb/1Pet.json'),
    '2Pet': () => require('../../assets/scripture/bsb/2Pet.json'),
    '1John': () => require('../../assets/scripture/bsb/1John.json'),
    '2John': () => require('../../assets/scripture/bsb/2John.json'),
    '3John': () => require('../../assets/scripture/bsb/3John.json'),
    Jude: () => require('../../assets/scripture/bsb/Jude.json'),
    Rev: () => require('../../assets/scripture/bsb/Rev.json'),
  },
  tam_irv: {
    Gen: () => require('../../assets/scripture/tam_irv/Gen.json'),
    Exod: () => require('../../assets/scripture/tam_irv/Exod.json'),
    Lev: () => require('../../assets/scripture/tam_irv/Lev.json'),
    Num: () => require('../../assets/scripture/tam_irv/Num.json'),
    Deut: () => require('../../assets/scripture/tam_irv/Deut.json'),
    Josh: () => require('../../assets/scripture/tam_irv/Josh.json'),
    Judg: () => require('../../assets/scripture/tam_irv/Judg.json'),
    Ruth: () => require('../../assets/scripture/tam_irv/Ruth.json'),
    '1Sam': () => require('../../assets/scripture/tam_irv/1Sam.json'),
    '2Sam': () => require('../../assets/scripture/tam_irv/2Sam.json'),
    '1Kgs': () => require('../../assets/scripture/tam_irv/1Kgs.json'),
    '2Kgs': () => require('../../assets/scripture/tam_irv/2Kgs.json'),
    '1Chr': () => require('../../assets/scripture/tam_irv/1Chr.json'),
    '2Chr': () => require('../../assets/scripture/tam_irv/2Chr.json'),
    Ezra: () => require('../../assets/scripture/tam_irv/Ezra.json'),
    Neh: () => require('../../assets/scripture/tam_irv/Neh.json'),
    Esth: () => require('../../assets/scripture/tam_irv/Esth.json'),
    Job: () => require('../../assets/scripture/tam_irv/Job.json'),
    Ps: () => require('../../assets/scripture/tam_irv/Ps.json'),
    Prov: () => require('../../assets/scripture/tam_irv/Prov.json'),
    Eccl: () => require('../../assets/scripture/tam_irv/Eccl.json'),
    Song: () => require('../../assets/scripture/tam_irv/Song.json'),
    Isa: () => require('../../assets/scripture/tam_irv/Isa.json'),
    Jer: () => require('../../assets/scripture/tam_irv/Jer.json'),
    Lam: () => require('../../assets/scripture/tam_irv/Lam.json'),
    Ezek: () => require('../../assets/scripture/tam_irv/Ezek.json'),
    Dan: () => require('../../assets/scripture/tam_irv/Dan.json'),
    Hos: () => require('../../assets/scripture/tam_irv/Hos.json'),
    Joel: () => require('../../assets/scripture/tam_irv/Joel.json'),
    Amos: () => require('../../assets/scripture/tam_irv/Amos.json'),
    Obad: () => require('../../assets/scripture/tam_irv/Obad.json'),
    Jon: () => require('../../assets/scripture/tam_irv/Jon.json'),
    Mic: () => require('../../assets/scripture/tam_irv/Mic.json'),
    Nah: () => require('../../assets/scripture/tam_irv/Nah.json'),
    Hab: () => require('../../assets/scripture/tam_irv/Hab.json'),
    Zeph: () => require('../../assets/scripture/tam_irv/Zeph.json'),
    Hag: () => require('../../assets/scripture/tam_irv/Hag.json'),
    Zech: () => require('../../assets/scripture/tam_irv/Zech.json'),
    Mal: () => require('../../assets/scripture/tam_irv/Mal.json'),
    Matt: () => require('../../assets/scripture/tam_irv/Matt.json'),
    Mark: () => require('../../assets/scripture/tam_irv/Mark.json'),
    Luke: () => require('../../assets/scripture/tam_irv/Luke.json'),
    John: () => require('../../assets/scripture/tam_irv/John.json'),
    Acts: () => require('../../assets/scripture/tam_irv/Acts.json'),
    Rom: () => require('../../assets/scripture/tam_irv/Rom.json'),
    '1Cor': () => require('../../assets/scripture/tam_irv/1Cor.json'),
    '2Cor': () => require('../../assets/scripture/tam_irv/2Cor.json'),
    Gal: () => require('../../assets/scripture/tam_irv/Gal.json'),
    Eph: () => require('../../assets/scripture/tam_irv/Eph.json'),
    Phil: () => require('../../assets/scripture/tam_irv/Phil.json'),
    Col: () => require('../../assets/scripture/tam_irv/Col.json'),
    '1Thess': () => require('../../assets/scripture/tam_irv/1Thess.json'),
    '2Thess': () => require('../../assets/scripture/tam_irv/2Thess.json'),
    '1Tim': () => require('../../assets/scripture/tam_irv/1Tim.json'),
    '2Tim': () => require('../../assets/scripture/tam_irv/2Tim.json'),
    Titus: () => require('../../assets/scripture/tam_irv/Titus.json'),
    Phlm: () => require('../../assets/scripture/tam_irv/Phlm.json'),
    Heb: () => require('../../assets/scripture/tam_irv/Heb.json'),
    Jas: () => require('../../assets/scripture/tam_irv/Jas.json'),
    '1Pet': () => require('../../assets/scripture/tam_irv/1Pet.json'),
    '2Pet': () => require('../../assets/scripture/tam_irv/2Pet.json'),
    '1John': () => require('../../assets/scripture/tam_irv/1John.json'),
    '2John': () => require('../../assets/scripture/tam_irv/2John.json'),
    '3John': () => require('../../assets/scripture/tam_irv/3John.json'),
    Jude: () => require('../../assets/scripture/tam_irv/Jude.json'),
    Rev: () => require('../../assets/scripture/tam_irv/Rev.json'),
  },
  tel_irv: {
    Gen: () => require('../../assets/scripture/tel_irv/Gen.json'),
    Exod: () => require('../../assets/scripture/tel_irv/Exod.json'),
    Lev: () => require('../../assets/scripture/tel_irv/Lev.json'),
    Num: () => require('../../assets/scripture/tel_irv/Num.json'),
    Deut: () => require('../../assets/scripture/tel_irv/Deut.json'),
    Josh: () => require('../../assets/scripture/tel_irv/Josh.json'),
    Judg: () => require('../../assets/scripture/tel_irv/Judg.json'),
    Ruth: () => require('../../assets/scripture/tel_irv/Ruth.json'),
    '1Sam': () => require('../../assets/scripture/tel_irv/1Sam.json'),
    '2Sam': () => require('../../assets/scripture/tel_irv/2Sam.json'),
    '1Kgs': () => require('../../assets/scripture/tel_irv/1Kgs.json'),
    '2Kgs': () => require('../../assets/scripture/tel_irv/2Kgs.json'),
    '1Chr': () => require('../../assets/scripture/tel_irv/1Chr.json'),
    '2Chr': () => require('../../assets/scripture/tel_irv/2Chr.json'),
    Ezra: () => require('../../assets/scripture/tel_irv/Ezra.json'),
    Neh: () => require('../../assets/scripture/tel_irv/Neh.json'),
    Esth: () => require('../../assets/scripture/tel_irv/Esth.json'),
    Job: () => require('../../assets/scripture/tel_irv/Job.json'),
    Ps: () => require('../../assets/scripture/tel_irv/Ps.json'),
    Prov: () => require('../../assets/scripture/tel_irv/Prov.json'),
    Eccl: () => require('../../assets/scripture/tel_irv/Eccl.json'),
    Song: () => require('../../assets/scripture/tel_irv/Song.json'),
    Isa: () => require('../../assets/scripture/tel_irv/Isa.json'),
    Jer: () => require('../../assets/scripture/tel_irv/Jer.json'),
    Lam: () => require('../../assets/scripture/tel_irv/Lam.json'),
    Ezek: () => require('../../assets/scripture/tel_irv/Ezek.json'),
    Dan: () => require('../../assets/scripture/tel_irv/Dan.json'),
    Hos: () => require('../../assets/scripture/tel_irv/Hos.json'),
    Joel: () => require('../../assets/scripture/tel_irv/Joel.json'),
    Amos: () => require('../../assets/scripture/tel_irv/Amos.json'),
    Obad: () => require('../../assets/scripture/tel_irv/Obad.json'),
    Jon: () => require('../../assets/scripture/tel_irv/Jon.json'),
    Mic: () => require('../../assets/scripture/tel_irv/Mic.json'),
    Nah: () => require('../../assets/scripture/tel_irv/Nah.json'),
    Hab: () => require('../../assets/scripture/tel_irv/Hab.json'),
    Zeph: () => require('../../assets/scripture/tel_irv/Zeph.json'),
    Hag: () => require('../../assets/scripture/tel_irv/Hag.json'),
    Zech: () => require('../../assets/scripture/tel_irv/Zech.json'),
    Mal: () => require('../../assets/scripture/tel_irv/Mal.json'),
    Matt: () => require('../../assets/scripture/tel_irv/Matt.json'),
    Mark: () => require('../../assets/scripture/tel_irv/Mark.json'),
    Luke: () => require('../../assets/scripture/tel_irv/Luke.json'),
    John: () => require('../../assets/scripture/tel_irv/John.json'),
    Acts: () => require('../../assets/scripture/tel_irv/Acts.json'),
    Rom: () => require('../../assets/scripture/tel_irv/Rom.json'),
    '1Cor': () => require('../../assets/scripture/tel_irv/1Cor.json'),
    '2Cor': () => require('../../assets/scripture/tel_irv/2Cor.json'),
    Gal: () => require('../../assets/scripture/tel_irv/Gal.json'),
    Eph: () => require('../../assets/scripture/tel_irv/Eph.json'),
    Phil: () => require('../../assets/scripture/tel_irv/Phil.json'),
    Col: () => require('../../assets/scripture/tel_irv/Col.json'),
    '1Thess': () => require('../../assets/scripture/tel_irv/1Thess.json'),
    '2Thess': () => require('../../assets/scripture/tel_irv/2Thess.json'),
    '1Tim': () => require('../../assets/scripture/tel_irv/1Tim.json'),
    '2Tim': () => require('../../assets/scripture/tel_irv/2Tim.json'),
    Titus: () => require('../../assets/scripture/tel_irv/Titus.json'),
    Phlm: () => require('../../assets/scripture/tel_irv/Phlm.json'),
    Heb: () => require('../../assets/scripture/tel_irv/Heb.json'),
    Jas: () => require('../../assets/scripture/tel_irv/Jas.json'),
    '1Pet': () => require('../../assets/scripture/tel_irv/1Pet.json'),
    '2Pet': () => require('../../assets/scripture/tel_irv/2Pet.json'),
    '1John': () => require('../../assets/scripture/tel_irv/1John.json'),
    '2John': () => require('../../assets/scripture/tel_irv/2John.json'),
    '3John': () => require('../../assets/scripture/tel_irv/3John.json'),
    Jude: () => require('../../assets/scripture/tel_irv/Jude.json'),
    Rev: () => require('../../assets/scripture/tel_irv/Rev.json'),
  },
};

/** Whole-chapter content. Returns null for unknown books or chapters. */
export function getChapter(
  bookOsis: string,
  chapter: number,
  translationId: string = selectedId,
): ChapterContent | null {
  const entry = bookByOsis(bookOsis);
  const load = BOOK_ASSETS[translationId]?.[bookOsis];
  if (!entry || !load || chapter < 1 || chapter > entry.chapters) return null;
  const asset = load() as BookAsset;
  const found = asset.chapters.find((item) => item.n === chapter);
  if (!found) return null;
  const blocks: ChapterBlock[] = found.blocks.map((block) =>
    block.t === 'h'
      ? { kind: 'heading', text: block.text }
      : { kind: 'verse', number: block.n ?? 0, text: block.text },
  );
  return {
    bookOsis,
    bookName: asset.name,
    chapter,
    blocks,
    verseCount: blocks.filter((block) => block.kind === 'verse').length,
  };
}

/** Plain verse text, e.g. the daily verse. Null when absent. */
export function getVerseText(
  bookOsis: string,
  chapter: number,
  verse: number,
  translationId: string = selectedId,
): string | null {
  const content = getChapter(bookOsis, chapter, translationId);
  if (!content) return null;
  const block = content.blocks.find(
    (item): item is { kind: 'verse'; number: number; text: string } =>
      item.kind === 'verse' && item.number === verse,
  );
  return block ? block.text : null;
}
