#!/usr/bin/env python3
"""Build bundled BSB Scripture assets from the local bsb/ dataset.

Reads bsb/api/BSB (never committed, see .gitignore) and writes:
  apps/mobile/assets/scripture/bsb/<OSIS>.json  one compact file per book
  apps/mobile/src/content/books.ts              book registry (names, chapters)

Only verse/heading text is kept; footnote markers and line breaks collapse
to a single space. Run from the repo root:
  python3 tools/build-bsb-assets.py
"""
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BSB = os.path.join(ROOT, "bsb", "api", "BSB")
ASSETS = os.path.join(ROOT, "apps", "mobile", "assets", "scripture", "bsb")
BOOKS_TS = os.path.join(ROOT, "apps", "mobile", "src", "content", "books.ts")

# BSB dataset id -> OSIS-style code used in canonical keys.
OSIS = {
    "GEN": "Gen", "EXO": "Exod", "LEV": "Lev", "NUM": "Num", "DEU": "Deut",
    "JOS": "Josh", "JDG": "Judg", "RUT": "Ruth", "1SA": "1Sam", "2SA": "2Sam",
    "1KI": "1Kgs", "2KI": "2Kgs", "1CH": "1Chr", "2CH": "2Chr", "EZR": "Ezra",
    "NEH": "Neh", "EST": "Esth", "JOB": "Job", "PSA": "Ps", "PRO": "Prov",
    "ECC": "Eccl", "SNG": "Song", "ISA": "Isa", "JER": "Jer", "LAM": "Lam",
    "EZK": "Ezek", "DAN": "Dan", "HOS": "Hos", "JOL": "Joel", "AMO": "Amos",
    "OBA": "Obad", "JON": "Jon", "MIC": "Mic", "NAM": "Nah", "HAB": "Hab",
    "ZEP": "Zeph", "HAG": "Hag", "ZEC": "Zech", "MAL": "Mal",
    "MAT": "Matt", "MRK": "Mark", "LUK": "Luke", "JHN": "John", "ACT": "Acts",
    "ROM": "Rom", "1CO": "1Cor", "2CO": "2Cor", "GAL": "Gal", "EPH": "Eph",
    "PHP": "Phil", "COL": "Col", "1TH": "1Thess", "2TH": "2Thess", "1TI": "1Tim",
    "2TI": "2Tim", "TIT": "Titus", "PHM": "Phlm", "HEB": "Heb", "JAS": "Jas",
    "1PE": "1Pet", "2PE": "2Pet", "1JN": "1John", "2JN": "2John", "3JN": "3John",
    "JUD": "Jude", "REV": "Rev",
}


def plain_text(items):
    parts = [it if isinstance(it, str) else " " for it in items]
    return re.sub(r"\s+", " ", "".join(parts)).strip()


def main():
    with open(os.path.join(BSB, "books.json"), encoding="utf-8") as fh:
        catalog = json.load(fh)
    os.makedirs(ASSETS, exist_ok=True)
    registry = []
    total_bytes = 0
    for entry in catalog["books"]:
        bsb_id = entry["id"]
        osis = OSIS[bsb_id]
        name = entry.get("commonName") or entry["name"]
        order = entry["order"]
        testament = "OT" if order <= 39 else "NT"
        chapters = []
        for num in range(1, entry["numberOfChapters"] + 1):
            with open(os.path.join(BSB, bsb_id, f"{num}.json"), encoding="utf-8") as fh:
                chapter = json.load(fh)["chapter"]
            blocks = []
            for block in chapter["content"]:
                kind = block.get("type")
                if kind == "heading":
                    blocks.append({"t": "h", "text": plain_text(block["content"])})
                elif kind == "verse":
                    blocks.append(
                        {"t": "v", "n": block["number"], "text": plain_text(block["content"])}
                    )
            chapters.append({"n": num, "blocks": blocks})
        payload = {"osis": osis, "bsb": bsb_id, "name": name, "chapters": chapters}
        path = os.path.join(ASSETS, f"{osis}.json")
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(payload, fh, ensure_ascii=False, separators=(",", ":"))
        total_bytes += os.path.getsize(path)
        registry.append(
            {"osis": osis, "bsb": bsb_id, "name": name,
             "chapters": entry["numberOfChapters"], "testament": testament}
        )
    lines = [
        "/** Generated by tools/build-bsb-assets.py — do not hand-edit. */",
        "export interface BookEntry {",
        "  osis: string;",
        "  bsb: string;",
        "  name: string;",
        "  chapters: number;",
        "  testament: 'OT' | 'NT';",
        "}",
        "",
        "export const BOOKS: BookEntry[] = [",
    ]
    for item in registry:
        lines.append(
            f"  {{ osis: '{item['osis']}', bsb: '{item['bsb']}', "
            f"name: '{item['name']}', chapters: {item['chapters']}, "
            f"testament: '{item['testament']}' }},"
        )
    lines += [
        "];",
        "",
        "const byOsis = new Map(BOOKS.map((book) => [book.osis, book]));",
        "",
        "export function bookByOsis(osis: string): BookEntry | null {",
        "  return byOsis.get(osis) ?? null;",
        "}",
        "",
        "export function booksByTestament(testament: 'OT' | 'NT'): BookEntry[] {",
        "  return BOOKS.filter((book) => book.testament === testament);",
        "}",
        "",
    ]
    os.makedirs(os.path.dirname(BOOKS_TS), exist_ok=True)
    with open(BOOKS_TS, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"books: {len(registry)}, asset bytes: {total_bytes}")


if __name__ == "__main__":
    main()
